name: Flash Device

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  flash:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r .github/workflows/helpers/requirements.txt

      - name: Build firmware
        run: |
            cmake --preset=Debug
            cmake --build --preset=Debug

      - name: Flash the device
        env:
          PROJECT_DIR: ${{ github.workspace }}
          # could hide this path in a secret if needed, for testing i dont care
          PATH: $PATH:/home/eddie/st/stm32cubeclt_1.17.0/STM32CubeProgrammer/bin/STM32_Programmer_CLI
        run: |
          python .github/workflows/helpers/flash_device.py